version: '3'
services:
  web:
    container_name: assistant-housework
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/src/
      - node_modules_volume:/usr/src/node_modules
    ports:
      - "3000:3000"
      - "4000:4000"
      - "5000:5000"
      - "5001:5001"
      - "9005:9005"
volumes: 
  node_modules_volume:
