roles: 
  documentId: string
  role: string

status: 
  documentId: string
  state: string(register | setting | running | calculation)

users:
  documentId: uid
  userId: string(uid) # 一応持たせる
  nickName: string
  roleRef: Ref/Role.documentId
  createdAt: Date
  updatedAt: Date

  currentWatchUser: {
    id: string | null,
    statusRef: Ref/status.documentId,
    inviteAddress: string
  }
  
  assistantUserIds: # アシスタントユーザIDの一覧
    documentId: string(assistantUserId)
    assistantUserId: string # 一応持たせる
    createdAt: Date
    updatedAt: Date

  ## アシストしてる承認者一覧
  assistToApprovers:
    documentId: string(assistToApproverId)
    assistToApproverId: string # 一応持たせる
    createdAt: Date
    updatedAt: Date

      items:
        documentId: auto
        itemId: string(documentId)
        label: string
        price: number
        createdAt: Date
        updatedAt: Date

      budgets:
        documentId: auto
        year: string
        month: string
        budget: number
        createdAt: Date
        updatedAt: Date

      deals:
        documentId: auto
        fullDate: Date
        year: string
        month: string
        date: string
        day: string（曜日）
        itemId: string(items-itemId) 
        itemLabel: string(items-name)
        price: number
        createdAt: Date
        updatedAt: Date

    
    

