# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ feature/firestore-rules ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: java install
      run: apt-get install -y openjdk-8-jre
    - name: Install Firebase
      run: npm install -g firebase-tools
    - name: Install Dependencies
      run: yarn install
    - name: test 
      run: yarn run firestore & yarn run test
    # TODO: 後ほど、buildは追記改修  
    # - name: Build Next.js
    #   run: npm run export
    # - name: Deploy to Firebase Hosting
    #   run: firebase deploy --token $FIREBASE_TOKEN
    #   env:
    #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_COLOR: '#3278BD'
        # SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Merged Master branch'
        # SLACK_TITLE: Post Title
        SLACK_USERNAME: Github Actions
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}